{
  "os": "linux",
  "dist": "trusty",
  "sudo": "required",
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "group": "stable",
  "addons": {
    "chrome": "stable"
  },
  "node_js": "10.15",
  "language": "node_js",
  "before_script": [
    "npm install -g @angular/cli@7.2.2",
    "npm install -g ionic"
  ],
  "script": [
    "ng lint",
    "ionic build browser --verbose"
  ]
}